// @flow

export const defaultCheckout: { 
    staffMemberName: string,
    id: string,
    apiId: number,
    nonTipOutBarSales: string,
    numberOfBottlesSold: string,
    lunchOrDinner: string,
    sales: string,
    grossSales: string,
    barSales: string,
    ccTips: string,
    cashTips: string,
    ccAutoGrat: string,
    cashAutoGrat: string,
    hours: string,
    staffMemberId: number,
    jobWorkedTitle: string,
    stringDate: string,
    barSpecialLine: string,
    saSpecialLine: string, }
    = { staffMemberName: "",
      id: "",
      apiId: 0,
      nonTipOutBarSales: '0',
      numberOfBottlesSold: '0',
      lunchOrDinner: "dinner",
      sales: '0',
      grossSales: '0',
      barSales: '0',
      ccTips: '0',
      cashTips: '0',
      ccAutoGrat: '0',
      cashAutoGrat: '0',
      hours: '',
      staffMemberId: -1,
      jobWorkedTitle: "",
      stringDate: "",
      barSpecialLine: '0',
      saSpecialLine: '0',
    };

export const defaultEarning: {
autoGratuity: number,
cashPayedForTipout: number,
cashTips: number,
ccTips: number,
id: number,
jobWorked: string,
lunchOrDinner: string,
owedCashForTipOut: boolean,
totalTipsForPayroll: number,
} = {
  autoGratuity: 0,
  cashPayedForTipout: 0,
  cashTips: 0,
  ccTips: 0,
  id: -1,
  jobWorked: '',
  lunchOrDinner: '',
  owedCashForTipOut: false,
  totalTipsForPayroll: 0,
};