export const LOAD_SERVICE_STAFF_SUCCESS = "LOAD_SERVICE_STAFF_SUCCESS";
export const POST_STAFF_MEMBER_SUCCESS = "POST_STAFF_MEMBER_SUCCESS";
export const LOAD_ALL_JOBS_SUCCESS = "LOAD_ALL_JOBS_SUCCESS";

