export const LOAD_SERVICE_STAFF_SUCCESS = "LOAD_SERVICE_STAFF_SUCCESS";
export const POST_STAFF_MEMBER_SUCCESS = "POST_STAFF_MEMBER_SUCCESS";
export const LOAD_ALL_JOBS_SUCCESS = "LOAD_ALL_JOBS_SUCCESS";
export const LOAD_APPROVED_JOBS_SUCCESS = "LOAD_APPROVED_JOBS_SUCCESS";
export const LOAD_APPROVED_STAFF_SUCCESS = "LOAD_APPROVED_STAFF_SUCCESS"; 
export const APPROVED_JOB_SELECTED_SUCCESS ="APPROVED_JOB_SELECTED_SUCCESS"; 

export const UPDATE_STAFF_MEMBER_SUCCESS = "UPDATE_STAFF_MEMBER_SUCCESS";
export const UPDATE_STAFF_MEMBER_NAME_SUCCESS = "UPDATE_STAFF_MEMBER_NAME_SUCCESS";

export const BEGIN_AXIOS_CALL = "BEGIN_AXIOS_CALL";
export const AXIOS_ERROR = "AXIOS_ERROR";

export const LOAD_CHECKOUTS_SUCCESS = "LOAD_CHECKOUTS_SUCCESS";
export const ADD_CHECKOUT_SUCCESS = "ADD_CHECKOUT_SUCCESS";
export const CREATE_CHECKOUT_MAP_SUCCESS = "CREATE_CHECKOUT_MAP_SUCCESS";

export const SET_STARTDATE_SUCCESS = "SET_STARTDATE_SUCCESS";
export const SET_INITIAL_START_DATE = "SET_INITIAL_START_DATE";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";


